### ISSUE TITLE
Make cake-sentry available via packagist for composer installation

### ISSUE THREAD

**Issue by johannesnagl** [Sandreu/cake-sentry#9]
Hi Sandreu,

it would be cool, if you could make your repo available via [packagist](https://packagist.org/about).

if you need help, please keep me posted.

**Comment by jtraulle** [comment]
Hey, can you tag a release for composer dependencies ?

Thanks :wink:

**Comment by mfn** [comment]
Yeah, that would be great :+1:

**Comment by Sandreu** [comment]
This is done.
Regards

**Comment by jtraulle** [comment]
Thank you :smile:
